### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by zaherab** [Abhishek-Raj-Poudel/animate-on-scroll-website#1]
Hello 
Thank you for your amazing code and tutorial but on animateOnScroll.js file is missing. please can you push it to git?
thank you

**Comment by Abhishek-Raj-Poudel** [comment]
Ok bro Iet me look into it

**Comment by Abhishek-Raj-Poudel** [comment]
Bro I just replaced the project with another one so that it works properly. Just clone the project again ok.
